---
foreman_db_username: foreman
foreman_db_password: supersecret$42

bind_zone_master_server_ip: 172.16.2.1

mysql_databases: 
  - name: foreman
    collation: utf8_unicode_ci
    encoding: utf8

mysql_users: 
  - name: "{{ foreman_db_username }}"
    host: localhost
    password: "{{ foreman_db_password }}"
    priv: "{{ foreman_db_username }}.*:ALL"

isc_dhcp_server_subnet:
  - netaddress: 172.16.2.0
    netmask: 255.255.255.0
    gateway: 172.16.2.1
    domain: foreman-net.local
    domain_search: foreman-net.local
    dns: "{{ bind_zone_master_server_ip }}"
    range: 172.16.2.101 172.16.2.200

default_zone: internal
firewalld__zone_interface:
  external: enp0s3
  internal: enp0s8
  trusted: enp0s9
firewalld_service_rules:
  dhcp:
    state: enabled
    zone: internal
  dns:
    state: enabled
    zone: internal
  http:
    state: enabled
    zone: internal
  https:
    state: enabled
    zone: internal
  puppetmaster:
    state: enabled
    zone: internal
  tftp:
    state: enabled
    zone: internal    

bind_allow_query: ['localhost', '172.16.2.0/24']
bind_listen_ipv4: ['any']
bind_recursion: true
bind_allow_recursion: ['localhost', '172.16.2.0/24']
bind_dnssec_validation: false

bind_zone_name: foreman-net.local
bind_zone_networks: ['172.16.2']
bind_zone_name_servers: ['foreman-net.local']
bind_zone_hosts:
  - name: pxe
    ip: 172.16.2.1
    aliases:
      - '@'
      - ns
      - foreman