---
foreman_db_username: foreman
foreman_db_password: supersecret$42

fqdn: pxe.foreman-net.local
fqdn_short: "{{ fqdn.split('.') | first }}"
hostname_fqdn: "{{ fqdn }}"
hosts_extra_localhosts:
  - "{{ fqdn }}"
  - "{{ fqdn_short }}"

mysql_databases: 
  - name: foreman
    collation: utf8_unicode_ci
    encoding: utf8

mysql_users: 
  - name: {{ foreman_db_username }}
    host: localhost
    password: {{ foreman_db_password }}
    priv: "{{ foreman_db_username }}.*:ALL"

isc_dhcp_server_subnet:
  - netaddress: 192.168.121.0
    netmask: 255.255.255.0
    gateway: 192.168.121.1
    domain: lab.local
    domain_search: lab.local
    dns: 192.168.121.1
    range: 192.168.121.20 192.168.121.100

default_zone: internal
firewalld__zone_interface:
  external: enp0s3
  internal: enp0s8
  trusted: enp0s9
firewalld_service_rules:
  dhcp:
    state: enabled
    zone: internal
  dns:
    state: enabled
    zone: internal
  http:
    state: enabled
    zone: internal
  https:
    state: enabled
    zone: internal
  puppetmaster:
    state: enabled
    zone: internal
  tftp:
    state: enabled
    zone: internal
