---
foreman_db_username: foreman
foreman_db_password: supersecret$42

bind_zone_master_server_ip: 172.16.2.1

mysql_databases: 
  - name: foreman
    collation: utf8_unicode_ci
    encoding: utf8

mysql_users: 
  - name: "{{ foreman_db_username }}"
    host: localhost
    password: "{{ foreman_db_password }}"
    priv: "{{ foreman_db_username }}.*:ALL"

isc_dhcp_server_subnet:
  - netaddress: 172.16.2.0
    netmask: 255.255.255.0
    gateway: 172.16.2.1
    domain: foreman-net.local
    domain_search: foreman-net.local foreman.local
    dns: "{{ bind_zone_master_server_ip }}"
    range: 192.168.121.101 192.168.121.200

default_zone: internal
firewalld__zone_interface:
  external: enp0s3
  internal: enp0s8
  trusted: enp0s9
firewalld_service_rules:
  dhcp:
    state: enabled
    zone: internal
  dns:
    state: enabled
    zone: internal
  http:
    state: enabled
    zone: internal
  https:
    state: enabled
    zone: internal
  puppetmaster:
    state: enabled
    zone: internal
  tftp:
    state: enabled
    zone: internal
