---
foreman_db_username: foreman
foreman_db_password: supersecret$42

mysql_databases: 
  - name: foreman
    collation: utf8_unicode_ci
    encoding: utf8

mysql_users: 
  - name: "{{ foreman_db_username }}"
    host: localhost
    password: "{{ foreman_db_password }}"
    priv: "{{ foreman_db_username }}.*:ALL"

isc_dhcp_server_subnet:
  - netaddress: 192.168.121.0
    netmask: 255.255.255.0
    gateway: 192.168.121.1
    domain: lab.local
    domain_search: lab.local
    dns: 192.168.121.1
    range: 192.168.121.20 192.168.121.100

network_connections:
  - name: "internal"
    type: "ethernet"
    interface_name: "enp0s8"
    zone: "internal"
    autoconnect: yes
    ip:
      dhcp4: no
      dns:
        - 172.16.2.1
      dns_search:
        - foreman-net.local
      auto6: no
      address:
        - 172.16.2.1/24
  - name: "external"
    type: "ethernet"
    interface_name: "enp0s3"
    zone: "external"
    autoconnect: yes
    ip:
      dhcp4: yes
      auto6: no
  - name: "trusted"
    type: "ethernet"
    interface_name: "enp0s9"
    zone: "trusted"
    autoconnect: yes
    ip:
      dhcp4: yes
      auto6: no

default_zone: internal
firewalld__zone_interface:
  external: enp0s3
  internal: enp0s8
  trusted: enp0s9
firewalld_service_rules:
  dhcp:
    state: enabled
    zone: internal
  dns:
    state: enabled
    zone: internal
  http:
    state: enabled
    zone: internal
  https:
    state: enabled
    zone: internal
  puppetmaster:
    state: enabled
    zone: internal
  tftp:
    state: enabled
    zone: internal
